### ISSUE TITLE
Footer on Certificate.php

### ISSUE THREAD

**Issue by shadowlion** [HeyAri/Center-4-Certification#5]
It floats to the top and blocks the certificate from being viewed.

**Comment by shadowlion** [comment]
The footer is floating like that because you made the certificate image background position absolute. I think there should be a better way to do this whole certificate thing, but will let you know what I can suggest.

**Comment by HeyAri** [comment]
I thought about setting a minimum space but wasn't sure on the distance

Ari
513.348.9120

On Jun 8, 2017, at 5:49 PM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:


The footer is floating like that because you made the certificate image background position absolute. I think there should be a better way to do this whole certificate thing, but will let you know what I can suggest.
